name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to project directory
        run: cd /home/ubuntu/sambhav-App

      - name: Build Docker images
        run: |
          docker-compose build
          # Add additional build steps if necessary

      - name: Push Docker images (if needed)
        run: |
          docker-compose push
          # Add additional push steps if necessary



        
        
  

   


      
   

      
  





