name: CI

on:
  push:
    branches:
      - master   # Ensure this matches your preferred default branch name

jobs:
  build_and_deploy:
    runs-on: self-hosted   # Indicates the job runs on your self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Change directory to application path
      run: cd /home/ubuntu/sambhav-App
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker-compose build
      




