name: CI

on:
  push:
    branches:
      - master   # Ensure this matches your preferred default branch name

jobs:
  build_and_deploy:
    runs-on: self-hosted   # Indicates the job runs on your self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: /home/ubuntu/sambhav-App   # Specify the target path for checkout
        repository: Rahul7600/sambhav-App
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Change directory to application path
      run: cd /home/ubuntu/sambhav-App
      
    # Add further steps for your build and deployment process
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker-compose build
      
   

      
  





