name: CI

on:
  push:
    branches:
      - master   # Ensure this matches your preferred default branch name

jobs:
  build_and_deploy:
    runs-on: self-hosted   # Indicates the job runs on your self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # - name: Change directory to application path
    #   run: cd /home/ubuntu/sambhav-App
      
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      run: |
        rsync -avz -e 'ssh -o StrictHostKeyChecking=no -p 22' /home/ubuntu/actions-runner/nodedemo/sambhav-App/sambhav-App/* ubuntu@ec2-13-233-166-142.ap-south-1.compute.amazonaws.com:/var/www/nodedemo/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-13-233-166-142.ap-south-1.compute.amazonaws.com
        cd /var/www/nodedemo
        docker-compose build
        
        
  

   


      
   

      
  





