name: CI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      run: |
        git clone --depth 1 https://github.com/Rahul7600/sambhav-App.git .
        git config --global user.name "rahul"
        git config --global user.email "rahu@gmail.com"
      
    - name: Build, Push, and Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ec2-user/sambhav-App
          docker-compose build
          docker-compose up -d
